language: node_js

node_js:
    - "6"

services:
    - docker

before_install:
    - npm install -g gulp
    - npm install -g bower

install:
    - npm install

script:
    - docker build -t alexandresneto/parking-app .

branches:
    only:
    - master
    - develop

after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - export REPO=parking-app
    - export VERSION=$(node -p -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8')).version")
    - docker tag $REPO $DOCKER_USERNAME/$REPO:$VERSION;
    - docker push $DOCKER_USERNAME/$REPO:$VERSION;
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker tag $REPO $DOCKER_USERNAME/$REPO;
        docker push $DOCKER_USERNAME/$REPO:latest;
      fi
