language: node_js

node_js:
    - "6"

services:
    - docker

before_install:
    - npm install -g gulp
    - npm install -g bower

install:
    - npm install

script:
    - export APP_NAME=parking-app
    - export VERSION=$(node -p -e "JSON.parse(require('fs').readFileSync('package.json', 'utf8')).version")
    - docker build -t $DOCKER_USERNAME/$APP_NAME:$VERSION .

branches:
    only:
    - master
    - develop

after_success:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    - docker push $DOCKER_USERNAME/$APP_NAME:$VERSION;
    - if [ "$TRAVIS_BRANCH" == "master" ]; then
        docker push $DOCKER_USERNAME/$APP_NAME:latest;
      fi
